[package]
name = "util"
version = "0.1.0"
edition = "2024"

[dependencies]
    ast = { path = "../ast" }
    thiserror = "2.0.12"
    derive_more = {version = "2.0.1", features = ["deref", "deref_mut"]}
